### ISSUE TITLE
Convert resulting buffer into something storable in a database

### ISSUE THREAD

**Issue by romandecker** [timhuff/canvas-phash#1]
Hello,

I'm trying to switch to your implementation of phash from `phash-image`, which gives me the hash of an image as a bigint. As phash-image uses libphash under the hood, its hashes are only 8-byte long. However the result of `canvas-phash`'s `getImageHash()` is a 128-byte buffer.

Are all bits of the 128 bytes significant? In the end I want to store the hashes of many images in a mysql database and then search for similar images via sql. With a 128-byte hash I would have to either split the hash across multiple columns, or use a binary/string column and some conversion during querying which would affect performance.

What solution would you suggest for a situation like this?

**Comment by timhuff** [comment]
Hi @DeX3. The algorithm works by basically breaking the image into a 16x16 grid of 256 cells. Each nibble of the 128-byte buffer represents color data for each cell. Not every bit is significant - only 3 bits out of every nibble is used, so you could compress it by removing every 4th `0` (though this will not be very significant, considering you're trying to get down to 8 bytes). A way you could get this down to an 8-byte buffer is by reducing the grid to a 4x4 grid. I'm not entirely sure how this will affect the algorithm. It will give you less granularity in fingerprinting the image and you might want to run some tests to determine how it impacts performance.

I'm not sure what scale you're working with but it would seem that there should be very little conversion necessary if you deal with a `Binary` field. The data is stored in `Buffer`s because it's meant to be kept in binary form. If performance of generating a hash is very important, there's an optimization that could be performed on lines `90-104` of `index.coffee`. A small modification could result in writing the bits straight to a `Buffer` (unfortunately, I don't currently have time to make this modification).

If you wish to reduce the grid to a 4x4, you could do so by using the code on the branch I just pushed: [8ByteBuffer](https://github.com/timhuff/canvas-phash/tree/8ByteBuffer). I haven't tested this but it should work.

**Comment by timhuff** [comment]
@DeX3 I'm going to go ahead and close this issue. If you decide to try the new branch, let me know how it treats you. Hope the modification fits your needs.

**Comment by romandecker** [comment]
@timhuff thanks for the input, I'll take a look :+1:
